name: petto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.0
  dartz: ^0.10.1
  easy_localization: ^3.0.7+1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_storage: ^12.4.5
  firebase_ui_firestore: ^1.7.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.2
  freezed_annotation: ^3.0.0
  go_router: ^15.1.1
  hooks_riverpod: ^2.6.1
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.19.0
  logger: ^2.5.0
  onesignal_flutter: ^5.3.0
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^2.9.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
